on:
  push:
    tags:
    - "cordoba-sdk/v[0-9]+.[0-9]+.[0-9]+"
jobs:
  publish:
    name: publish Cordoba SDK package
    if: startsWith(github.ref, 'refs/tags/cordoba-sdk')
    runs-on: self-hosted
    timeout-minutes: 15
    env:
      restoreProject: "GS_Cordoba.Rest.SDK/GS_Cordoba.Rest.SDK.csproj"
      pkgPath: "GS_Cordoba.Rest.SDK.nupkg"
      tagPath: "cordoba-sdk"
      nugetFeed: "https://api.nuget.org/v3/index.json"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6  

    - name: Verify commit exists in origin/master
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/master

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/$tagPath\/v/}" >> $GITHUB_ENV
      shell: bash

    - name: Restore Packages
      run: MSBuild GS_Cordoba.Rest.sln --% /t:restore /p:Configuration=Release /clp:Summary;ErrorsOnly /m

    - name: Build
      run: MSBuild GS_Cordoba.Rest.sln --% /p:Configuration=Release /clp:Summary;ErrorsOnly /m  

    - name: Pack
      run: nuget pack ${env:restoreProject} -IncludeReferencedProjects -OutputFileNamesWithoutVersion -Version ${env:VERSION} -Properties Configuration=Release 

    - name: Push
      run: nuget push ${env:pkgPath} ${{ secrets.NUGETAPI }} -Source ${env:nugetFeed}
