on:
  push:
    tags:
    - "ocs-sdk/v[0-9]+.[0-9]+.[0-9]+"
jobs:
  publish:
    name: publish OCS SDK package
    if: startsWith(github.ref, 'refs/tags/ocs-sdk')
    runs-on: [self-hosted, windows]
    timeout-minutes: 15
    env:
      restoreProject: "GS_OmniChannelSystem.Rest.SDK/GS_OmniChannelSystem.Rest.SDK.csproj"
      pkgPath: "GS_OmniChannelSystem.Rest.SDK"
      tagPath: "ocs-sdk"
      nugetFeed: "https://api.nuget.org/v3/index.json"
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Verify commit exists in origin/master
      shell: pwsh
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | Select-String origin/master

    - id: get_version
      name: Get version
      uses: jannemattila/get-version-from-tag@v4

    - name: Build
      run: dotnet build GS_OmniChannelSystem.Rest.sln -c Release
      shell: pwsh

    - name: Pack
      run: dotnet pack ${env:restoreProject} -p:PackageVersion=${{ steps.get_version.outputs.version }} -c Release
      shell: pwsh

    - name: Push
      run: dotnet nuget push ${env:pkgPath}.${{ steps.get_version.outputs.version }}.nupkg --api-key ${{ secrets.NUGETAPI }} --source ${env:nugetFeed}
      shell: pwsh
